config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "rooms#index"

  resources :messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room, inverse_of: :messages
  belongs_to :user

  validates :message, presence: true

  def as_json(options = nil)
    super(options).merge(
      created_at: created_at.strftime("%A, %d %b %Y %l:%M %p"),
      user_username: user.username,
      user_avatar_url: user.gravatar_url
    )
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy, inverse_of: :room

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :messages

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :current_room

  def create
    @message = Message.create(message_params.merge(user_id: current_user.id))
    RoomChannel.broadcast_to @room, @message
  end

  private

  def message_params
    params.require(:message).permit(:message, :room_id)
  end

  def current_room
    @room = Room.find(message_params["room_id"])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_rooms
  before_action :load_room, only: [:show, :edit, :update]

  def index
  end

  def show
    @messages = @room.messages.includes(:user)
    @message = @room.messages.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Room #{@room.name} was successfully created"
      redirect_to room_path(@room)
    else
      flash.now[:error] = "There was an error"
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      flash[:success] = "Room #{room.name} was successfully updated"
      redirect_to rooms_path
    else
      render :edit
    end
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def load_room
    @room = Room.find(params[:id])
  end

  def load_rooms
    @rooms = Room.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert-info"
    when :success then "alert-success"
    when :error then "alert-danger"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render partial: "shared/nav_bar" %>
    <%= render partial: "shared/flash_message" %>
    <div class="container mt-5">
      <div class="row">
        <div class="col-12">
           <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rooms/_chat_form.html.erb
<%= simple_form_for @message, remote: true do |form| %>
  <div class="input-group mb-3">
    <%= form.input :message, as: :string, wrapper: false, label: false, input_html: { class: 'chat-input text-secondary' } %>
    <div class="input-group-append">
      <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
    </div>
  </div>

  <%= form.input :room_id, as: :hidden %>
<% end %>

app/views/rooms/index.html.erb
<% content_for :chats do %>
  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the Chat App!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
<% end %>

<%= render  template: "rooms/rooms" %>

app/views/rooms/new.html.erb
<% content_for :chats do %>
  <div class="col">
    <h2> Add a new room </h2>
    <%= simple_form_for @room do |form| %>
      <%= form.input :name %>
      <%= form.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
<% end %>

<%= render  template: "rooms/rooms" %>

app/views/rooms/rooms.html.erb
<div class="row">
  <div class="col-12 col-md-3 mb-4">
    <div class="mb-3">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a room
      <% end %>
    </div>

    <% if @rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <%= link_to "##{room.name}", room_path(room), class: "nav-link room-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>
  </div>

  <%= yield :chats %>
</div>

app/views/rooms/show.html.erb
<% content_for :chats do %>
  <div class="col">
    <h1 class="mb-3 text-secondary"> #<%= @room.name %> </h1>

    <div class="chat border rounded bg-light p-3" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% if @messages.empty? %>
        <p class="text-center no-messages"> Start chatting...🤠 </p>
      <% end %>
      <% @messages.each do |message| %>
        <div class="row no-gutters mb-3">
          <div class="col-1 text-center">
            <img src="<%= message.user.gravatar_url %>" class="rounded-circle w-100" alt="">
          </div>

          <div class="col rounded bg-white border ml-3 px-3 py-2 text-primary">
            <small class="text-secondary">
              <strong><%= message.user.username %> </strong> • <%= message.created_at.strftime("%A, %d %b %Y %l:%M %p") %>
            </small>
            <div class="message-content">
              <p class="mb-1">
                <%= message.message %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= render partial: "chat_form" %>
  </div>
<% end %>

<%= render  template: "rooms/rooms" %>

<div class="d-none" data-role="message-template">
  <div class="row no-gutters mb-3">
    <div class="col-1 text-center">
      <img src="" class="rounded-circle w-100" alt="" data-role="user-avatar">
    </div>

    <div class="col rounded bg-white border ml-3 px-3 py-2 text-primary">
      <small class="text-secondary">
        <strong data-role="user-username"></strong> • <span data-role="message-date"></span>
      </small>
      <div class="message-content">
        <p class="mb-1" data-role="message-text"></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="flash alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
    <%= value %>
  </div>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between px-5">
  <a class="navbar-brand" href="#">Chat App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= current_user.gravatar_url %>">
        <%= current_user.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>